# Generated by Django 4.2.5 on 2024-01-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
